// Genlock
//
// HSYNC and VSYNC is generated by Dual Hero System and distributed by MewPro Genlock Dongle
//


#ifdef USE_GENLOCK

void startGenlock()
{
  switch (td[TD_MODE]) {
  case MODE_PHOTO:
  case MODE_BURST:
    delay(500); // delay for LED light to be visible
    ledOff();
    break;
  default:
    break;
  }
}

void stopGenlock()
{
  memcpy((char *)buf, "\203FN\013", 4);
  SendBufToCamera();
}

void setupGenlock()
{
}

void checkGenlock()
{
}

#else

unsigned long previous_shutter;
unsigned long timelapse = 0;

void startGenlock()
{
  switch (td[TD_MODE]) {
  case MODE_PHOTO:
  case MODE_BURST:
    delay(500); // delay for LED light to be visible
    ledOff();
    break;
  case MODE_TIMELAPSE:
    timelapse = (unsigned long)td[TD_PHOTO_XSEC] * 1000;
    if (timelapse == 0) {
      timelapse = 500;
    }
    break;
  default:
    break;
  }
  previous_shutter = millis();
}

void stopGenlock()
{
  timelapse = 0;
  // video stops at FALLING edge in MASTER NORMAL mode
  digitalWrite(TRIG, LOW);
  delay(1);
  digitalWrite(TRIG, HIGH);
}

void setupGenlock()
{
  pinMode(TRIG, OUTPUT); digitalWrite(TRIG, HIGH);
}

void checkGenlock()
{
  if (timelapse == 0) {
    return;
  }
  if (!waiting && millis() - previous_shutter >= timelapse) {
    queueIn("SY2");
    previous_shutter = millis();
  }
}

#endif
